#steps:
#  - name: maven:3.6.0-jdk-11-slim
#    entrypoint: 'mvn'
#    args: ['install']

steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: 'mvn'
    args: ['install']

  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']